# Generated by Django 4.1.3 on 2024-05-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_alter_game_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamer',
            field=models.IntegerField(),
        ),
    ]
